/**
 * FinanceCalc — PDF Generation Utility (Lazy-loaded)
 * This module is dynamically imported only when the user clicks "Download PDF"
 */

export async function generatePDF(title, summary, tableData, tableColumns) {
    // Dynamic import to keep the initial bundle small
    const { default: jsPDF } = await import('jspdf');
    const { default: autoTable } = await import('jspdf-autotable');

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, pageWidth, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('FinanceCalc', 14, 18);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(title, 14, 28);

    // Date
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, pageWidth - 14, 28, { align: 'right' });

    // Summary section
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Results Summary', 14, 50);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);

    let yPos = 60;
    summary.forEach(({ label, value }) => {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(15, 23, 42);
        doc.text(label + ':', 14, yPos);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(37, 99, 235);
        doc.text(String(value), 80, yPos);
        yPos += 8;
    });

    // Table
    if (tableData && tableData.length > 0 && tableColumns) {
        doc.setTextColor(15, 23, 42);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Detailed Breakdown', 14, yPos + 10);

        autoTable(doc, {
            startY: yPos + 18,
            head: [tableColumns.map(c => c.header)],
            body: tableData.map(row => tableColumns.map(c => c.accessor(row))),
            styles: {
                fontSize: 8,
                cellPadding: 4,
            },
            headStyles: {
                fillColor: [15, 23, 42],
                textColor: [255, 255, 255],
                fontStyle: 'bold',
            },
            alternateRowStyles: {
                fillColor: [248, 250, 252],
            },
            theme: 'grid',
        });
    }

    // Footer
    const finalY = doc.lastAutoTable?.finalY || yPos + 20;
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('This is an estimate for educational purposes only. Not financial advice.', 14, finalY + 15);
    doc.text('Generated by FinanceCalc — financecalc.com', 14, finalY + 22);

    // Disclaimer
    doc.setFontSize(7);
    doc.text('Results may vary. Please consult a qualified financial advisor for personalized advice.', 14, finalY + 28);

    doc.save(`${title.replace(/\s+/g, '_').toLowerCase()}_results.pdf`);
}

